name: Check README on PR

on:
  pull_request:
    branches:
        - master
  push:
    branches:
        - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
          name: checkout "${{ github.base_ref }}"
          with:
            fetch-depth: 1
            ref: ${{ github.base_ref }}
        - uses: actions/checkout@v4
          name: checkout "${{ github.head_ref }}"
          with:
            fetch-depth: 1
            ref: ${{ github.head_ref}}
        - name: check_diff
          shell: bash
          run: |
            FILES_CHANGED=$(git diff --name-only origin/${{ github.base_ref }}..${{ github.head_ref }})
            if echo "$FILES_CHANGED" | grep -q "README.md"; then
                echo "The file README.md has been updated."
            else
                echo "The file README.md has not been updated."
            exit 1
            fi