name: Check README on push

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check if README.md is updated
      run: |
        FILES_CHANGED=$(git diff --name-only HEAD~1 HEAD)
        if echo "$FILES_CHANGED" | grep -q "README.md"; then
          echo "The file README.md has been updated."
        else
          echo "The file README.md has not been updated."
          exit 1
        fi