name: check-release-note

on:
  release:
    types: [created]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Check if README.md is updated
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0)
        FILES_CHANGED=$(git diff --name-only $LAST_TAG HEAD)
        if echo "$FILES_CHANGED" | grep -q README.md; then
          echo "The file README.md has been updated."
        else
          echo "The file README.md has not been updated."
          exit 1
        fi